ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS avatar SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE direct_messages ADD COLUMN IF NOT EXISTS sender_avatar SMALLINT NOT NULL DEFAULT 1;
