ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(300);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(300);
ALTER TABLE direct_messages ADD COLUMN IF NOT EXISTS sender_avatar_url VARCHAR(300);
